---
- name: Restart a service
  hosts: localhost
  become: yes
  vars:
    service_name: nginx
  tasks:
    - name: Restart the service
      ansible.builtin.service:
        name: "{{ service_name }}"
        state: restarted
      notify: Check service status

  handlers:
    - name: Check service status
      ansible.builtin.command: systemctl status "{{ service_name }}"
      register: service_status
    
    - name: Show service status
      ansible.builtin.debug:
        var: service_status.stdout_lines